Repository caicloud/aloe, pull requests merged in 2019-01, with the labels that each got.

#33 chore(linter): delete gas from linter
  .gometalinter.json
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/XS

#35 add ddysher to approver
  OWNERS
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#36 feat(roundtrip): add when and loop logic
  Gopkg.lock
  examples/crud/server/server.go
  examples/crud/testdata/context.yaml
  examples/crud/testdata/get.yaml
  framework/context.go
  framework/framework.go
  matcher/matcher.go
  roundtrip/matcher.go
  runtime/construct.go
  runtime/context.go
  runtime/render.go
  runtime/roundtrip.go
  template/exist.go
  template/func.go
  template/lexer.go
  template/random.go
  template/template.go
  template/template_test.go
  types/roundtrip.go
  utils/jsonutil/array.go
  utils/jsonutil/helper.go
  utils/jsonutil/json.go
  utils/jsonutil/map.go
  utils/jsonutil/variable.go
  vendor/github.com/Knetic/govaluate/.gitignore
  vendor/github.com/Knetic/govaluate/.travis.yml
  vendor/github.com/Knetic/govaluate/CONTRIBUTORS
  vendor/github.com/Knetic/govaluate/EvaluableExpression.go
  vendor/github.com/Knetic/govaluate/EvaluableExpression_sql.go
  vendor/github.com/Knetic/govaluate/ExpressionToken.go
  vendor/github.com/Knetic/govaluate/LICENSE
  vendor/github.com/Knetic/govaluate/MANUAL.md
  vendor/github.com/Knetic/govaluate/OperatorSymbol.go
  vendor/github.com/Knetic/govaluate/README.md
  vendor/github.com/Knetic/govaluate/TokenKind.go
  vendor/github.com/Knetic/govaluate/benchmarks_test.go
  vendor/github.com/Knetic/govaluate/evaluationFailure_test.go
  vendor/github.com/Knetic/govaluate/evaluationStage.go
  vendor/github.com/Knetic/govaluate/evaluation_test.go
  vendor/github.com/Knetic/govaluate/expressionFunctions.go
  vendor/github.com/Knetic/govaluate/expressionOutputStream.go
  vendor/github.com/Knetic/govaluate/lexerState.go
  vendor/github.com/Knetic/govaluate/lexerStream.go
  vendor/github.com/Knetic/govaluate/parameters.go
  vendor/github.com/Knetic/govaluate/parsing.go
  vendor/github.com/Knetic/govaluate/parsingFailure_test.go
  vendor/github.com/Knetic/govaluate/parsing_test.go
  vendor/github.com/Knetic/govaluate/readme_test.go
  vendor/github.com/Knetic/govaluate/sanitizedParameters.go
  vendor/github.com/Knetic/govaluate/sql_test.go
  vendor/github.com/Knetic/govaluate/stagePlanner.go
  vendor/github.com/Knetic/govaluate/test.sh
  vendor/github.com/Knetic/govaluate/tokenExpressionFailure_test.go
  vendor/github.com/Knetic/govaluate/tokenKind_test.go
  vendor/github.com/Knetic/govaluate/tokenStream.go
  vendor/github.com/Knetic/govaluate/torture_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/XXL

#37 feat(label): add focus and skip for label selection
  .gometalinter.json
  .travis.yml
  aloe.go
  config/config.go
  examples/crud/crud.go
  examples/crud/testdata/get.yaml
  framework/framework.go
  hack/install-linter.sh
  runtime/roundtrip.go
  types/case.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/XL
