Repository caicloud/aloe, pull requests merged in 2019-02, with the labels that each got.

#42 feat(flag): add prefix for glog
  aloe.go
  utils/glog/flag.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#45 feat(preset): add path template for roundtrip template
  runtime/render.go
  runtime/roundtrip.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/S

#43 feat(framework): support custom client
  aloe.go
  framework/framework.go
  roundtrip/http.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M

#47 feat(exports): add variable exports of context and fix def bug of loop
  data/validation.go
  data/validation_test.go
  examples/crud/testdata/context.yaml
  examples/crud/testdata/delete.yaml
  examples/crud/testdata/get.yaml
  examples/crud/testdata/nested/context.yaml
  examples/crud/testdata/nested/get.yaml
  examples/crud/testdata/put.yaml
  examples/crud/testdata/verify.yaml
  framework/context.go
  framework/framework.go
  roundtrip/matcher.go
  runtime/construct.go
  runtime/context.go
  runtime/render.go
  runtime/roundtrip.go
  template/select.go
  types/context.go
  types/roundtrip.go
  types/var.go
  utils/jsonutil/array.go
  utils/jsonutil/helper.go
  utils/jsonutil/json.go
  utils/jsonutil/map.go
  utils/jsonutil/variable.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/XL

#48 chore(*): add bbbmj to OWNERS
  OWNERS
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#49 feat(matcher): add $match and $len matcher
  examples/crud/testdata/context.yaml
  examples/crud/testdata/delete.yaml
  examples/crud/testdata/get.yaml
  examples/crud/testdata/put.yaml
  framework/context.go
  framework/framework.go
  matcher/map.go
  matcher/matcher.go
  matcher/matcher_test.go
  matcher/slice.go
  matcher/sp.go
  runtime/render.go
  template/func.go
  template/len.go
  template/lexer.go
  template/select.go
  template/template.go
  template/template_test.go
  utils/jsonutil/array.go
  utils/jsonutil/helper.go
  utils/jsonutil/json.go
  utils/jsonutil/map.go
  utils/jsonutil/variable.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/XL

#50 fix(crash): fix conflict crash problem
  utils/jsonutil/helper.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#51 feat(when): add type conversion funcs for eval expression
  framework/context.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/S

#52 feat(multiclient): add support of multiple clients in roundtrip
  framework/framework.go
  roundtrip/http.go
  runtime/roundtrip.go
  types/roundtrip.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M

#53 feat(roundtrip): support absolute api path and fix render client bug
  runtime/render.go
  types/roundtrip.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M

#54 fix(response): fix response matcher problem when match in eventually
  roundtrip/matcher.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/S
